services:
  coral:
    image: nicolargo/glances:4.0.7-full
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    pid: host
    network_mode: host
    container_name: coral_glances
    tmpfs:
      - /app
    environment:
      - "GLANCES_OPT=-w"
    #Currently docker swarm mode on a specific node does not have appropriate permissions; using docker-compose for now
    #deploy:
    #  placement:
    #    constraints:
    #      - node.labels.hardware == coral
    #ports:
    #  - "61208:61208" # Glances web interface
