version: '3.9'


services:
  coral:
    image: nicolargo/glances:4.0.7-full
    deploy:
      placement:
        constraints:
          - node.labels.hardware == coral
    ports:
      - "61208:61208" # Glances web interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      GLANCES_OPT: "--disable-webui --quiet"
