version: '3.9'


services:
  coral:
    image: nicolargo/glances:4.0.7-full
    ports:
      - "61208:61208" # Glances web interface
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /app
    environment:
      - "GLANCES_OPT=-w"
    network_mode: host
    deploy:
      placement:
        constraints:
          - node.labels.hardware == coral
#    environment:
#      GLANCES_OPT: "--disable-webui --quiet"
