name: 'coral'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'coral.yaml'

jobs:
  deploy:
    runs-on: [coral]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a container command
        run: |
          docker-compose -f coral.yaml up -d
