name: 'glances'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a container command
        run: |
          docker stack deploy -c glances.yaml glances
